const fmt=n=>Number(n||0).toLocaleString('de-DE',{maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data={};
const state={view:'overall',page:1,pageSize:25,query:''};

function setSection(name){document.querySelectorAll('.hs-section').forEach(x=>x.classList.toggle('is-active',x.id===`section-${name}`));document.querySelectorAll('.hs-main-tab').forEach(x=>x.classList.toggle('is-active',x.dataset.section===name));}
function scoreOf(x,view){return view==='overall'?Number(x.totalPoints||0):Number(x.points||0)}
function rankedRows(view){const rows=[...(data.individual?.[view]||[])];return rows.sort((a,b)=>scoreOf(b,view)-scoreOf(a,view)||Number(a.rank||999)-Number(b.rank||999)||String(a.name).localeCompare(String(b.name),'de'))}
function renderPodium(){const rows=rankedRows(state.view).slice(0,3),el=document.querySelector('#podium');if(!rows.length){el.innerHTML='<div class="hs-podium-empty">Noch keine Ranglistendaten vorhanden.</div>';return}el.innerHTML=rows.map((x,i)=>`<article class="hs-podium-card place-${i+1}"><div class="hs-place-label">Platz ${i+1}</div><strong>${esc(x.name)}</strong><div class="hs-podium-points">${fmt(scoreOf(x,state.view))} Punkte</div>${state.view==='overall'?`<small>${fmt(x.matchdayWins)} Spieltagssiege</small>`:''}<div class="hs-pedestal-face" aria-hidden="true"><span>${i+1}</span></div></article>`).join('')}

function renderIndividual(){const all=rankedRows(state.view),q=state.query.trim().toLocaleLowerCase('de'),filtered=q?all.filter(x=>String(x.name).toLocaleLowerCase('de').includes(q)):all;const pages=Math.max(1,Math.ceil(filtered.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize,rows=filtered.slice(start,start+state.pageSize);const head=document.querySelector('#individual-head'),body=document.querySelector('#individual-body');
 if(state.view==='overall'){head.innerHTML='<tr><th>Rang</th><th>Spieler</th><th>Bonuspunkte</th><th>Spieltagsiege</th><th>Gesamtpunkte</th></tr>';body.innerHTML=rows.map(x=>`<tr><td class="hs-rank">${esc(x.rank)}</td><td>${esc(x.name)}</td><td>${fmt(x.bonusPoints)}</td><td>${fmt(x.matchdayWins)}</td><td>${fmt(x.totalPoints)}</td></tr>`).join('');document.querySelector('#individual-title').textContent='Einzelwertung – Gesamt';document.querySelector('#individual-caption').textContent='Gesamtübersicht aller Einzelspieler.'}
 else{head.innerHTML='<tr><th>Rang</th><th>Spieler</th><th>Punkte</th><th>Bonus</th><th>Gesamtpunkte</th><th>Spieltagsplatz</th></tr>';body.innerHTML=rows.map(x=>`<tr><td class="hs-rank">${esc(x.rank)}</td><td>${esc(x.name)}</td><td>${fmt(x.points)}</td><td>${fmt(x.bonusPoints)}</td><td>${fmt(x.totalPoints)}</td><td>${esc(x.matchdayRank)}</td></tr>`).join('');document.querySelector('#individual-title').textContent='Einzelwertung – Spieltag';document.querySelector('#individual-caption').textContent=data.meta?.matchday||'Ausgewählter Einzelspieltag'}
 if(!rows.length)body.innerHTML='<tr><td colspan="6" class="hs-empty">Keine passenden Spieler gefunden.</td></tr>';document.querySelector('#page-info').textContent=`Seite ${state.page} von ${pages} · ${filtered.length} Spieler`;document.querySelector('#page-prev').disabled=state.page<=1;document.querySelector('#page-next').disabled=state.page>=pages;renderPodium();}

function renderTeam(name){const overall=(data.teams?.overall||[]).find(x=>x.name===name),matchday=(data.teams?.matchday||[]).find(x=>x.name===name),host=document.querySelector(`[data-team-name="${CSS.escape(name)}"]`);if(!host)return;host.innerHTML=`<div class="hs-team-hero"><div><div class="hs-eyebrow">Gruppierung</div><h2>${esc(name)}</h2><p class="hs-status">Gesamt- und Spieltagswertung dieser Gruppierung.</p></div><div class="hs-team-score">${fmt(overall?.totalPoints)}<small>Gesamtpunkte</small></div></div><div class="hs-team-stats"><article><span>Gesamtrang</span><strong>${esc(overall?.rank??'–')}</strong></article><article><span>Spieltagsiege</span><strong>${fmt(overall?.matchdayWins)}</strong></article><article><span>Bonuspunkte</span><strong>${fmt(overall?.bonusPoints)}</strong></article><article><span>Aktueller Spieltag</span><strong>${fmt(matchday?.points)} Punkte</strong></article><article><span>Spieltagsrang</span><strong>${esc(matchday?.matchdayRank??'–')}</strong></article><article><span>Tippspieltag</span><strong>${esc(data.meta?.matchday||'–')}</strong></article></div>`}

function renderRecords(){const i=rankedRows('overall'),m=rankedRows('matchday'),t=[...(data.teams?.overall||[])].sort((a,b)=>Number(b.totalPoints||0)-Number(a.totalPoints||0)),r=data.records||{};const values=[['Tabellenführer',i[0]?`${i[0].name} · ${fmt(i[0].totalPoints)}`:'Noch offen'],['Höchster Spieltag',r.highestMatchdayScore?`${r.highestMatchdayScore.name} · ${fmt(r.highestMatchdayScore.points)}`:'Noch offen'],['Meiste Spieltagssiege',r.mostMatchdayWins?`${r.mostMatchdayWins.name} · ${fmt(r.mostMatchdayWins.wins)}`:'Noch offen'],['Vorsprung an der Spitze',`${fmt(r.leadMargin)} Punkte`],['Bestes Team',r.bestTeam?`${r.bestTeam.name} · ${fmt(r.bestTeam.points)}`:'Gleichstand'],['Teilnehmer',`${i.length} Spieler`]];document.querySelector('#record-grid').innerHTML=values.map(x=>`<article class="hs-record-card"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong></article>`).join('');
 const orders=[['K','Kapitän der Woche',m[0]&&Number(m[0].points)>0?`${m[0].name} · ${fmt(m[0].points)} Punkte`:'Noch nicht vergeben'],['V','Volltrefferkönig','Benötigt Detaildaten zu exakten Tipps'],['A','Aufholjäger','Benötigt Rangverlauf mehrerer Spieltage'],['S','Heißeste Serie','Benötigt mehrere abgeschlossene Spieltage'],['U','Überraschung des Spieltags','Benötigt Tipp- und Quotendetails'],['M','Admiral des Monats','Wird nach dem ersten vollständigen Monat vergeben']];document.querySelector('#order-grid').innerHTML=orders.map(x=>`<article class="hs-order-card"><span>${esc(x[1])}</span><strong>${esc(x[2])}</strong></article>`).join('');
 const history=data.history||[];document.querySelector('#history-grid').innerHTML=history.length?history.map(x=>`<div class="hs-history-row"><span>${esc(x.matchday)}</span><strong>${esc(x.leader)}</strong><b>${fmt(x.points)} Punkte</b></div>`).join(''):'<p class="hs-empty">Die Saisonhistorie beginnt automatisch, sobald mehrere Spieltagsstände archiviert wurden.</p>';}

function init(){const i=rankedRows('overall'),m=rankedRows('matchday'),t=[...(data.teams?.overall||[])].sort((a,b)=>Number(b.totalPoints||0)-Number(a.totalPoints||0));document.querySelector('#summary-leader').textContent=i[0]?.name||'–';document.querySelector('#summary-leader-points').textContent=`${fmt(i[0]?.totalPoints)} Punkte`;document.querySelector('#summary-matchday').textContent=data.meta?.matchday||'–';document.querySelector('#summary-matchday-winner').textContent=m[0]&&Number(m[0].points)>0?`${m[0].name} · ${fmt(m[0].points)} Punkte`:'Noch ohne Wertung';const tied=t.length<2||Number(t[0]?.totalPoints||0)===Number(t[1]?.totalPoints||0);document.querySelector('#summary-team').textContent=tied?'Gleichstand':t[0].name;document.querySelector('#summary-team-points').textContent=`${fmt(t[0]?.totalPoints)} Punkte`;document.querySelector('#summary-updated').textContent=data.meta?.exportDate||'–';renderIndividual();renderTeam('Old Smugglers Team');renderTeam('New Smugglers Team');renderRecords();
 document.querySelectorAll('.hs-main-tab').forEach(b=>b.addEventListener('click',()=>setSection(b.dataset.section)));document.querySelectorAll('[data-individual-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-individual-view]').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');state.view=b.dataset.individualView;state.page=1;renderIndividual()}));document.querySelector('#player-search').addEventListener('input',e=>{state.query=e.target.value;state.page=1;renderIndividual()});document.querySelector('#page-size').addEventListener('change',e=>{state.pageSize=Number(e.target.value);state.page=1;renderIndividual()});document.querySelector('#page-prev').addEventListener('click',()=>{if(state.page>1){state.page--;renderIndividual()}});document.querySelector('#page-next').addEventListener('click',()=>{state.page++;renderIndividual()});}
fetch('./highscore.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(d=>{data=d;init()}).catch(e=>{document.querySelector('#individual-body').innerHTML='<tr><td class="hs-empty">Highscore-Daten konnten nicht geladen werden.</td></tr>';console.error(e)});
